### ISSUE TITLE
Statistical Foundations of Learning is missing

### ISSUE THREAD

**Issue by Vozf** [Vuenc/TUM-Master-Informatics-Offered-Lectures#2]
And probably some more courses renamed to cit are also missing

**Comment by Vozf** [comment]
https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses?$ctx=design=ca;lang=en&$skip=0&curriculumVersionId=4731&objTermId=198&orgId=1&q=CIT

**Comment by Vuenc** [comment]
Hi, indeed some courses are missing (also see the warning I added to the README).
Unfortunately when moving to the CIT website they also removed the table of offered electives modules instead of updating it :( since I used that table as a basis, I couldn't update the list properly anymore

I'm already working on a new solution where I scrape the data from this TUM online tree view [https://campus.tum.de/tumonline/wbstpcs.showSpoTree?pStpStpNr=4731](https://campus.tum.de/tumonline/wbstpcs.showSpoTree?pStpStpNr=4731). Which was a bit more work, but will hopefully also mean I can fully automate this process in the future. I hope I'll be able to publish that new version soon

**Comment by Vozf** [comment]
I have it in german. My language is english and I'm logged in. Btw similar personal table in english can be accesed in tumonline -> curriculum -> informatics https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/wbstpcs.showSpoTree?$ctx=design=ca2;header=max;lang=en&pSJNr=1615&pStStudiumNr=1075417&pStartSemester=&pStpStpNr=4731

**Comment by Vozf** [comment]
Thanks for the quick fix

**Comment by Vozf** [comment]
Just taken a look at the new pages. Awesome work

**Comment by Vuenc** [comment]
Thanks!
