### ISSUE TITLE
[Suggestion] Add Donation Section Below Disclaimer

### ISSUE THREAD

**Issue by fehmisener** [Vuenc/TUM-Master-Informatics-Offered-Lectures#8]
I've been using this repo since the start of my master's program, and now that I'm almost done, I still rely on it. It's helped me a ton, so I feel like I should contribute something back.

It would be great if you have a **donation section** below the disclaimer, **buymeacoffee** or maybe set up **GitHub Sponsorships**. I can help with it in my free time—you just need to provide your details!

**Comment by Vuenc** [comment]
By the way, in case you're interested in contributing to the repo: I've been wanting to add more degree programs to the list (but haven't had enough time to actually do it). I think there are a lot of smaller CIT school study programs besides Informatics and DEA which also have some kind of elective component with different elective areas, and their students will probably face similar problems as we do when trying to find electives to take. I think it would be relatively easy to also list those with the existing code, but they probably differ in small details (like the THEO in Informatics), and I haven't had time to look into it.

So a task could be to identify suitable degree programs, and find out in what way their curriculum trees differ (and how the parsing code needs to be changed). This is just an idea in case you're interested in collaborating :)

**Comment by fehmisener** [comment]
> By the way, in case you're interested in contributing to the repo: I've been wanting to add more degree programs to the list (but haven't had enough time to actually do it). I think there are a lot of smaller CIT school study programs besides Informatics and DEA which also have some kind of elective component with different elective areas, and their students will probably face similar problems as we do when trying to find electives to take. I think it would be relatively easy to also list those with the existing code, but they probably differ in small details (like the THEO in Informatics), and I haven't had time to look into it.
> 
> So a task could be to identify suitable degree programs, and find out in what way their curriculum trees differ (and how the parsing code needs to be changed). This is just an idea in case you're interested in collaborating :)

I'm actually working on something similar for the entire university. You can check it out [here](https://nerd.sse.cit.tum.de). It includes filters (though some may not be working) and detailed information about courses. The issue is that I'm not using the **course section** on TUMonline to fetch course details. Instead, I'm using an old **module handbook**, which results in a lot of courses—many of which are outdated and not currently offered.

The reason I'm using the **module handbook** is that it provides additional information for filtering, such as **degree programs**, **ECTS**, and **language**, which the TUMonline course section typically lacks.

**Feel free to share your feedback!**

**Comment by Vuenc** [comment]
Hey, cool project!

Feedback: I especially like that you can filter by an ECTS range, that will be useful to many. The main issue I see with it right now that it doesn't allow to filter by degree program, but only by general area (like STEM). The data seems to be pretty up to date, e.g. I can find the course Legged Robots which according to my data was first offered this summer (I just wondered because you said you were using an old module handbook).

The data about the degree programs a course counts for should be available from TUM online (it's displayed as "Status within Curriculum" on each course page). The number of credits is also there, it technically depends on the curriculum though (probably very rare that it's different for different curricula, but I've seen it happen once for a practical course I took). This is the part of the reason why I started to merge different data sources for this repository, maybe this would work for you too. But I saw that you're investigating the use of NLP techniques in your project, so maybe that's not your focus.

Btw, thanks a lot for you donation :D
